### ISSUE TITLE
Sources?

### ISSUE THREAD

**Issue by Cinerar** [ketetefid/StorijOS#1]

**Comment by ketetefid** [comment]
As the OS has heavily modified files in the vanilla Gentoo, I have to find which files I have edited; check each of them one by one; create the corresponding ebuilds and add them to the repository. This is going to be time-consuming, but I will finally get it done. Don't worry.

**Comment by multikatt** [comment]
So it's been over a year since your last comment and there's still no sources available as far as I can tell. How's it coming along?

**Comment by ketetefid** [comment]
I was able to allocate some time to it and scan all the changes that I had made to the original gentoo. The current step is the ebuild writing and I need to consult the Gentoo dev group to get some questions answered.
Since v 1.2.4 I have decided to put out the repo first before releasing any newer version. Sorry that it has taken longer than expected. I have been busy very much.

**Comment by ketetefid** [comment]
Closing this, finally.
