### ISSUE TITLE
Is it massively complex to setup WiFi rather than ethernet?

### ISSUE THREAD

**Issue by pigd0g** [ketetefid/StorijOS#12]
Could you provide a guide on enabling Wifi?

**Comment by ketetefid** [comment]
This is on the plan to let the user choose which interface s/he wants (ethernet or wifi). Basically:

1- You need to edit /etc/conf.d/net and add:
modules_wlan0="wpa_supplicant"
config_wlan0="dhcp"

Instead of dhcp use the same values you see for eth0. repeat each line and replace _eth0 with _wlan0

2- Edit /etc/wpa_supplicant/wpa_supplicant.conf and enter the credentials of your WPA2 wifi here. Add:
          ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=wheel
          network={
                ssid="YourSSID-NAme"
                scan_ssid=1
                eap=TLS
                proto=WPA2
                group=CCMP TKIP
                pairwise=CCMP TKIP
                priority=5
                key_mgmt=WPA-PSK
                psk="Your-wifi-password"
          }
Then:

/etc/inti.d/net.eth0 stop && /etc/init.d/wlan0 start

You need to experiment it a bit. If everything was OK, finally you need to add net.wlan0 to startup and delete net.eth0.

If you are not experienced, it is better to wait until this feature is implemented.

**Comment by pigd0g** [comment]
Thanks, I'll wait for the blockchain to verify and then give it a go.

Will it be easy to upgrade the distro?

Also, off-topic - I used a 16Gb USB stick as its all I had on hand, I'll pickup a 32Gb - I should be able to clone the contents from one to another right? Without having to download and verify again?

**Comment by ketetefid** [comment]
About upgrading, the functionality is there, but it needs to be implemented for convenience in the UI.
About the stick, you are fine for a few months with that until you have to change it to 32GB. You can change it but it needs some steps which are not difficult actually.

**Comment by ketetefid** [comment]
If you still need more assistance, please consult the forums or the siaberry reddit /r/siaberry as those places are more appropriate.
